// Edit this file to customize your statements and which axes they affect.
// Each question has `text` and an `effect` object mapping axis keys to weights.
// Positive weight means agreeing boosts the RIGHT side, negative boosts the LEFT side.
// hist: { left: "Yhorm", right: "Pacal" },
// val: { left: "Frakk",   right: "Porg"   },
// prog: { left: "Owl",  right: "Abe" },
// cult:  { left: "The People", right: "Inami" }
// Positive numbers boost the right label; negative numbers boost the left.


const QUESTIONS = [
  { text: "Public services should be funded even if it requires higher taxes.", effect: { hist: 1, prog: -1 } }, 
  { text: "Abortion is an immoral act that should be banned or significantly limited..", effect: { hist:  -1, val: 1, prog: 1  } },
  { text: "Topping a twink is not as gay as getting pegged", effect: { hist:  1, prog: 1  } },
  { text: "Traditional values should be preserved even as society changes.", effect: { hist:  -1, val: 1, prog: 2, cult: 1   } },
  { text: "Some people and their ancestors have a quality of excellence that gives them the right to lead others.", effect: { hist:  -1, cult: 2 } },
  { text: "Morality is subjective.", effect: { hist: 1, val: -1 } },
  { text: "I can ride a horse.", effect: { cult: 1 } },
  { text: "Cannibalism is always immoral.", effect: { hist:   -1, val: 1  } },
  { text: "I believe gender is independent of assigned sex.", effect: { hist: 1, val: -1, prog: -1 } },
  { text: "I would shoot the students manning the barricades.", effect: { hist: -1 } },
  { text: "Humans exist in a hierarchy for a reason, some deserve to be at the top, while others do not.", effect: { hist: -1, prog: 1, cult: 1 } },
  { text: "I would rather be a peasant in the modern day than a king in medieval times", effect: { hist: 1, } },
  { text: "I consider myself woke.", effect: { val: -1, hist: 1, prog: -1 } },
  { text: "I'd be comfortable in a polyamorous relationship.", effect: { val: -1, cult: -1 } },
  { text: "I am lazy and cannot be bothered to write my own questions", effect: { val: 1 } },
  { text: "I have broken into Chesterton's grave and stolen his bones.", effect: { val: 1 } },
  { text: "I'm interested in millitary technology.", effect: { valu: -1, prog: 1 } },
  { text: "I have at least 3 servants in my main residence.", effect: { val: -1, cult: -1 } },
  { text: "Nutrition is a liberal invention to keep you from the grind.", effect: {hist: -1 } },
  { text: "I was on the discord server in 2020.", effect: { val: 1, cult: -1 } },
  { text: "I am a paneuropist.", effect: { hist: 1, prog: -1, cult: -1 } },
  { text: "I believe some peoples are superior to others which gives them the right to rule over the inferior.", effect: { hist: -1, prog: 1 } },
  { text: "Okay actually I'm just straight up racist.", effect: { hist: -1, prog: 1 } },
  { text: "I chew on plastic.", effect: { cult: -1 , hist: 1 , val: 1 } },
  { text: "Foreign intervention is sometimes necessary.", effect: {cult: 1 } },    
  { text: "I believe in God.", effect: { val: 1, hist: -1 } },
  { text: "Freer the market the freer the people.", effect: { hist: -1, cult: 1 } },
  { text: "A real gentleman always opens the door for a lady.", effect: { cult: 1, prog: 1 } },
  { text: "I support LGBTQ+.", effect: {cult: -1 } },
  { text: "Mainstream history is dominated by biased assumptions that always support the perceived underdog.", effect: {hist: -1 } },
  { text: "I like firearms.", effect: {prog: 1, cult: 1 } },
  { text: "Kill all poor people.", effect: {cult: 1, prog: 1} },
  { text: "We need to keep our nation armed to stop other nations with authotarian ambitions from achieving them.", effect: {hist: -1, cult: 1 } },
  { text: "There should be no billionaires.", effect: {hist: 1, prog: -1, cult: -1 } },
  { text: "It is perfectly fine to be intimate with friends without being in a romantic relationship.", effect: {val: -1 } },
  { text: "Taxes should be abolished.", effect: {prog: 1 } },
  { text: "Brown people shouldn't speak to me.", effect: {prog: 1 } },
  { text: "People should be thankful to men that serve their country in the military.", effect: {prog: 1, cult: 1 } },
  { text: "The history of all hitherto existing society is the history of class struggles.", effect: {hist: 1, prog: -1, cult: -1 } },
  { text: "I will complain this test wasn't funny enough.", effect: {val: 1 } },
  { text: "I like to treat myself well with little gifts.", effect: {cult: 1 } },
  { text: "People should just stop complaining and actually do stuff.", effect: {hist: -1, prog: 1 } },
  { text: "I deserve respect.", effect: {hist: -1, cult: 1 } },
  { text: "A", effect: {hist: -1, val: 1, prog: -1, cult: -1 } },
];
